global using MediatR;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using NerdStore.Catalog.Application.Abstractions;
global using NerdStore.Catalog.Application.AutoMapper;
global using NerdStore.Catalog.Application.Services;
global using NerdStore.Catalog.Application.ViewModels;
global using NerdStore.Catalog.Data;
global using NerdStore.Catalog.Data.Repository;
global using NerdStore.Catalog.Domain.Abstractions;
global using NerdStore.Catalog.Domain.Events;
global using NerdStore.Catalog.Domain.Services;
global using NerdStore.Core.Abstractions;
global using NerdStore.Core.Bus;
global using NerdStore.WebApp.MVC.Configuration;
global using NerdStore.WebApp.MVC.Data;
global using System.Reflection;

